services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data